[package]
name = "plots"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.18"
rusqlite = { version = "0.32", features = ["bundled"] }
polars = { version = "0.46", features = ["parquet"] }
